UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=1' WHERE Id = 1
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=2' WHERE Id = 2
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=3' WHERE Id = 3
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=4' WHERE Id = 4
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=5' WHERE Id = 5
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=6' WHERE Id = 6
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=7' WHERE Id = 7
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=8' WHERE Id = 8
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=9' WHERE Id = 9
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=10' WHERE Id = 10
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=11' WHERE Id = 11
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=12' WHERE Id = 12
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=13' WHERE Id = 13
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=14' WHERE Id = 14
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=15' WHERE Id = 15
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=16' WHERE Id = 16
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=17' WHERE Id = 17
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=18' WHERE Id = 18
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=19' WHERE Id = 19
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=20' WHERE Id = 20
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=21' WHERE Id = 21
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=22' WHERE Id = 22
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=23' WHERE Id = 23
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=24' WHERE Id = 24
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=25' WHERE Id = 25
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=26' WHERE Id = 26
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=27' WHERE Id = 27
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=28' WHERE Id = 28
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=29' WHERE Id = 29
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=30' WHERE Id = 30
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=31' WHERE Id = 31
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=32' WHERE Id = 32
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=33' WHERE Id = 33
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=34' WHERE Id = 34
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=35' WHERE Id = 35
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=36' WHERE Id = 36
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=37' WHERE Id = 37
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=38' WHERE Id = 38
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=39' WHERE Id = 39
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=40' WHERE Id = 40
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=41' WHERE Id = 41
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=42' WHERE Id = 42
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=43' WHERE Id = 43
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=44' WHERE Id = 44
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=45' WHERE Id = 45
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=46' WHERE Id = 46
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=47' WHERE Id = 47
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=48' WHERE Id = 48
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=49' WHERE Id = 49
UPDATE Walker SET ImageUrl = 'https://api.dicebear.com/9.x/pixel-art/svg?seed=50' WHERE Id = 50
